SHEET_HINT_KEYWORDS = [
    "question",
    "requirement",
    "assessment",
    "audit",
    "score",
    "評分",
    "問題",
    "問項",
    "稽核",
    "自評",
]

COLUMN_KEYWORDS = {
    "question": [
        "question",
        "requirement",
        "item",
        "內容",
        "問題",
        "問項",
        "要求",
        "條文",
    ],
    "score": [
        "score",
        "rating",
        "point",
        "分數",
        "評分",
        "得分",
    ],
    "owner": [
        "owner",
        "function",
        "department",
        "pic",
        "負責",
        "單位",
        "部門",
    ],
    "answer": [
        "answer",
        "response",
        "comment",
        "description",
        "回覆",
        "回答",
        "說明",
    ],
    "evidence": [
        "evidence",
        "reference",
        "document",
        "依據",
        "佐證",
        "文件",
    ],
    "question_id": [
        "id",
        "no",
        "item no",
        "編號",
        "項次",
    ],
}
